name:               "candyless"
description:        "candy monster is running"

url:                ""
author:             "thinker3197"
twitter:            "candyless"
email:              "candyless@163.com"
github:             "candyless"
pinterest:          "candyless"
avatar_url:         /resources/img/avatar-cut.png

disqus_shortname:   "thinker3197"

background:         /resources/img/w-5273.jpg

paginate:           4
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate