name:               "candyless"
description:        "candy monster is running"

url:                ""
author:             "candyless"
email:              "candyless@163.com"
twitter:            "candyless"
email:              "candyless@163.com"
github:             "candyless"
pinterest:          "candyless"
linkedin:           "candyless"
facebook:           "candyless"
avatar_url:         /resource/img/avatar-cut.png

disqus_shortname:   "candyless"

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           4
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate